// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqZy8wjHsaoJgmfC9vLXntNaz6nVQnZEk',
    appId: '1:856994908218:web:ff51a334db1c1ec1878d03',
    messagingSenderId: '856994908218',
    projectId: 'medimind-4d6a4',
    authDomain: 'medimind-4d6a4.firebaseapp.com',
    storageBucket: 'medimind-4d6a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1xLbJ3_UljaG9CvwJ8MzO3X_y1OCQV8k',
    appId: '1:856994908218:android:e818aca78e05acc7878d03',
    messagingSenderId: '856994908218',
    projectId: 'medimind-4d6a4',
    storageBucket: 'medimind-4d6a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4kRvImfRvYhFJ8AiHFGkxMh0pLBcjRwQ',
    appId: '1:856994908218:ios:901d02c89a2c77e3878d03',
    messagingSenderId: '856994908218',
    projectId: 'medimind-4d6a4',
    storageBucket: 'medimind-4d6a4.firebasestorage.app',
    iosBundleId: 'com.example.medimind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4kRvImfRvYhFJ8AiHFGkxMh0pLBcjRwQ',
    appId: '1:856994908218:ios:901d02c89a2c77e3878d03',
    messagingSenderId: '856994908218',
    projectId: 'medimind-4d6a4',
    storageBucket: 'medimind-4d6a4.firebasestorage.app',
    iosBundleId: 'com.example.medimind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqZy8wjHsaoJgmfC9vLXntNaz6nVQnZEk',
    appId: '1:856994908218:web:672b2d773c81005f878d03',
    messagingSenderId: '856994908218',
    projectId: 'medimind-4d6a4',
    authDomain: 'medimind-4d6a4.firebaseapp.com',
    storageBucket: 'medimind-4d6a4.firebasestorage.app',
  );
}
